type TemplateState = {
  id: string;
  title: string;
  description: string;
  imageUrl: string;
  topicId: string;
  customString1State: string;
  customString1Question: string;
  customString2State: string;
  customString2Question: string;
  customString3State: string;
  customString3Question: string;
  customString4State: string;
  customString4Question: string;
  customInt1State: string;
  customInt1Question: string;
  customInt2State: string;
  customInt2Question: string;
  customInt3State: string;
  customInt3Question: string;
  customInt4State: string;
  customInt4Question: string;
  customText1State: string;
  customText1Question: string;
  customText2State: string;
  customText2Question: string;
  customText3State: string;
  customText3Question: string;
  customText4State: string;
  custom_text4_question: string;
  customCheckbox1State: string;
  customCheckbox1Question: string;
  customCheckbox2State: string;
  customCheckbox2Question: string;
  customCheckbox3State: string;
  customCheckbox3Question: string;
  customCheckbox4State: string;
  customCheckbox4Question: string;
};
export const getInitialTemplateState = (): TemplateState => {
  return {
    id: "",
    title: "",
    description: "",
    imageUrl: "",
    topicId: "",
    customString1State: "not-present",
    customString1Question: "",
    customString2State: "not-present",
    customString2Question: "",
    customString3State: "not-present",
    customString3Question: "",
    customString4State: "not-present",
    customString4Question: "",
    customInt1State: "not-present",
    customInt1Question: "",
    customInt2State: "not-present",
    customInt2Question: "",
    customInt3State: "not-present",
    customInt3Question: "",
    customInt4State: "not-present",
    customInt4Question: "",
    customText1State: "not-present",
    customText1Question: "",
    customText2State: "not-present",
    customText2Question: "",
    customText3State: "not-present",
    customText3Question: "",
    customText4State: "not-present",
    custom_text4_question: "",
    customCheckbox1State: "not-present",
    customCheckbox1Question: "",
    customCheckbox2State: "not-present",
    customCheckbox2Question: "",
    customCheckbox3State: "not-present",
    customCheckbox3Question: "",
    customCheckbox4State: "not-present",
    customCheckbox4Question: "",
  };
};
